### Récupération des posts pour pcastrec
GET http://localhost:5000/posts
### Création d'un post pour pcastrec
POST http://localhost:5000/posts
Content-Type: application/json
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZSI6IjYxYThkYTRmY2QzZDJmOTIzZjk1Y2E3OSIsInVpZCI6IjM0YWNiNDc2LTBiOWItNDAwYy04Mjk1LWRmNDRmOGE4MTM3ZiIsImlhdCI6MTYzODk1NTAwNywiZXhwIjoxNjM5MDQxNDA3fQ.LyFgwFTPjiklVANe2JE1b5x5ElTMIaIvC_azmsIM3S0
uid: 34acb476-0b9b-400c-8295-df44f8a8137f

{
    "title": "Lorem Ipsum",
    "content": "Le lorem ipsum est, en imprimerie, une suite de mots sans signification utilisée à titre provisoire pour calibrer une mise en page, le texte définitif venant remplacer le faux-texte dès qu'il est prêt ou que la mise en page est achevée. Généralement, on utilise un texte en faux latin, le Lorem ipsum ou Lipsum."
}