### rcastrec send friend invite to pcastrec
POST http://localhost:5000/relations
Content-Type: application/json
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZSI6IjYxYThkYTZkY2QzZDJmOTIzZjk1Y2E3ZiIsInVpZCI6ImRmNTViMGMxLTZjZTQtNDc3MS1iM2JiLTc4ODVkMmY5YzgxNiIsImlhdCI6MTYzOTA1NTAwNSwiZXhwIjoxNjM5MTQxNDA1fQ.u3Kft87GnGMkbuTEZ0Zsoglu6xEfPpowN2qdRIyTEB4
uid: df55b0c1-6ce4-4771-b3bb-7885d2f9c816

{
    "uid": "61a8da4fcd3d2f923f95ca79"
}
### rcastrec envoie une demande d'ami a pcastrec
GET http://localhost:5000/relations?status=PENDING
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYTc4OTRjMDdhNDM3MjMwYzljZWUzNyIsInVpZCI6IjA4NzdjNWQ3LTg4YmYtNGNkYi05NDU0LTBmZWM0NTU5ZGFhNSIsImlhdCI6MTYzODQ1MjgyMSwiZXhwIjoxNjM4NTM5MjIxfQ.X2qtqvN4D5Hbl9sLQnaeO7J-5fxYXvJvTRkrXyl8d-E
uid: 0877c5d7-88bf-4cdb-9454-0fec4559daa5
###
PUT http://localhost:5000/relations/61a62877d52d9128eacabd83
Content-Type: application/json
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYTYyNWQ0ZDUyZDkxMjhlYWNhYmQ3OCIsInVpZCI6ImM0Yzg4OGQ3LWYzZDUtNDJhNC05YTdiLTY4MGI3YWFmNWY4MSIsImlhdCI6MTYzODI3OTMyNywiZXhwIjoxNjM4MzY1NzI3fQ.KStpzilniXMQhUjlNzSbveswZoZttUyz8f1RJH2hbCE; Path=/; HttpOnly; Secure; SameSite=Lax
uid: c4c888d7-f3d5-42a4-9a7b-680b7aaf5f81

{
    "status": "RESOLVE"
}