GET http://localhost:5000/users
Content-Type: application/json
uid: 9a6cdcc5-29dd-4357-97de-ae6a3a9468c3
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOWQyNmVmZDA0NzdkN2MzNzhkNGYxZiIsInVpZCI6IjEzN2ZjMGNhLWFiNzktNDc3Yy04YTZlLTc2YjIxODYxYzc5OCIsImlhdCI6MTYzNzY4OTA3MywiZXhwIjoxNjM3Nzc1NDczfQ.tqluCfUhpoLvkdkc3p2PFajw5tXupmUH97wEwNI2D_U; Path=/; HttpOnly; Secure; SameSite=Lax
###
GET http://localhost:5000/users/619d26efd0477d7c378d4f1f/articles
Content-Type: application/json
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOWQyNmVmZDA0NzdkN2MzNzhkNGYxZiIsInVpZCI6IjlhNmNkY2M1LTI5ZGQtNDM1Ny05N2RlLWFlNmEzYTk0NjhjMyIsImlhdCI6MTYzNzc0MTU5MiwiZXhwIjoxNjM3ODI3OTkyfQ.s2mMDAN8SzZdyg51EZBYKxJ822F6vz7aQTOHLGGa6zU; Path=/; HttpOnly; Secure; SameSite=Lax
uid: 9a6cdcc5-29dd-4357-97de-ae6a3a9468c3
###
DELETE http://localhost:5000/users/619cc758e6235d7198fdef60
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOWNjNzQwZTYyMzVkNzE5OGZkZWY1YyIsInVpZCI6ImQwN2I5MDU1LTM0ZTAtNGJiOS1hOTY3LTBhZGViZDEzMDk5OCIsImlhdCI6MTYzNzY2NDYyOSwiZXhwIjoxNjM3NzUxMDI5fQ.tTaV4uOMNdnM4iLpoo7Zy6RI4oVXklSF54bBYuBdrfY; Path=/; HttpOnly; Secure; SameSite=Lax
uid: d07b9055-34e0-4bb9-a967-0adebd130998